routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Route::resource('server', 'ServerController')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Player.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Player extends Model
{
    protected $fillabe = array('username', 'UUID');

}

app/Server.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Server extends Model
{
    protected $fillabe = array('ip', 'build', 'name', 'discord_id', 'total_jogadores', 'banned_players');
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password', 'server_name',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ServerController.php
<?php

namespace App\Http\Controllers;

use App\Server;
use App\Player;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;

class ServerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.server.serverIndex')->withServers(Server::All());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
     
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Server  $server
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $servers = Server::find($id);
        $players = Player::where('server_id', $id)->get();

        return view('pages.server.serverShow', [
            "users" => $players,
            "server" => $servers
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Server  $server
     * @return \Illuminate\Http\Response
     */
    public function edit(Server $server)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Server  $server
     * @return \Illuminate\Http\Response
     */
    public function update($id)
    {
        $rules = array(
            'discord_id' => 'required|numeric'
        );
        $validator = Validator::make(Input::all(), $rules);

        if ($validator->fails()) {
            return Redirect::to('server/' . $id . '/edit')
                ->withErrors($validator);
        } else {
            
            $server = Server::find($id);
            $server->discord_id = Input::get('discord_id');
            $server->save();
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Server  $server
     * @return \Illuminate\Http\Response
     */
    public function destroy(Server $server)
    {
        //
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    public function list() {
        $result = User::All();
        return view('pages/UserList')->withUsers($result);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                    <a class="dropdown-item" href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>
                    
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <title>MineManager</title>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <!-- Bootstrap Core CSS -->
    <link href="{{ asset('/plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('/plugins/perfect-scrollbar/css/perfect-scrollbar.css') }}" rel="stylesheet">
    <!-- This page CSS -->
    <!-- chartist CSS -->
    <link href="{{ asset('/plugins/chartist-js/dist/chartist.min.css') }}" rel="stylesheet">

    <link href="{{ asset('/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.css') }}" rel="stylesheet">
    <!--c3 CSS -->
    <link href="{{ asset('/plugins/c3-master/c3.min.css') }}" rel="stylesheet">
    <!--Toaster Popup message CSS -->
    <link href="{{ asset('/plugins/toast-master/css/jquery.toast.css') }}" rel="stylesheet">
    <!-- Custom CSS -->
    @yield('styles')
    <link href="{{ asset('/css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('/css/pages/dashboard1.css') }}" rel="stylesheet">
    <link href="{{ asset('/css/colors/megna-dark.css') }}" id="theme" rel="stylesheet">
</head>

<body class="fix-header fix-sidebar card-no-border">

    <div class="preloader">
        <div class="loader">
            <div class="loader__figure"></div>
            <p class="loader__label">Mine Manager</p>
        </div>
    </div>

    <div id="main-wrapper">

        <header class="topbar">
            <nav class="navbar top-navbar navbar-expand-md navbar-light">
                <!-- ============================================================== -->
                <!-- Logo -->
                <!-- ============================================================== -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="index-2.html">
                        <!-- Logo icon --><b>
                            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                            <!-- Dark Logo icon -->
                            <!-- Light Logo icon -->
                            <i class="fa fa-chart-area d-none"></i>
							<i class="fa fa-chart-area text-white"></i>
                        </b>
                        <!--End Logo icon -->
                        <!-- Logo text --><span class="text-white"> 
                         <!-- dark Logo text -->
                         MineManager</span> </a>
                </div>

                <div class="navbar-collapse">
                    <ul class="navbar-nav mr-auto">
                        <!-- This is  -->
                        <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                        <li class="nav-item"> <a class="nav-link sidebartoggler hidden-sm-down waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                    </ul>
                    <ul class="navbar-nav my-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle waves-effect waves-dark" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="flag-icon flag-icon-br"></i></a>
                            <div class="dropdown-menu dropdown-menu-right animated bounceInDown"> <a class="dropdown-item" href="#"><i class="flag-icon flag-icon-us"></i>English</a></div>
                        </li>
                        <li class="nav-item dropdown">
                            @guest

                            @else
                                <a class="nav-link dropdown-toggle waves-effect waves-dark" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->username }}</a>
                                <div class="dropdown-menu dropdown-menu-right animated flipInY">
                                    <ul class="dropdown-user">
                                        <li>
                                            <div class="dw-user-box">
                                                <div class="u-text">
                                                    <h4>{{ Auth::user()->username }}</h4>
                                                    <p class="text-muted">{{ Auth::user()->email }}</p>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            @endguest
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
						<li class="active">
							<a class="waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-gauge"></i><span class="hide-menu">Dashboard</span></a>
						</li>
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>

        <div class="page-wrapper">
            <div class="container-fluid">
                @yield('content')
			</div>
        </div>

    </div>

    <script src="{{ asset('/plugins/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('/plugins/bootstrap/js/popper.min.js') }}"></script>
    <script src="{{ asset('/plugins/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('/js/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ asset('js/waves.js') }}"></script>
    <script src="{{ asset('/js/sidebarmenu.js') }}"></script>
    <script src="{{ asset('/js/custom.min.js') }}"></script>
    <script src="{{ asset('/plugins/sparkline/jquery.sparkline.min.js') }}"></script>
    {{-- <script src="{{ asset('/plugins/chartist-js/dist/chartist.min.js') }}"></script> --}}
    {{-- <script src="{{ asset('/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.min.js') }}"></script> --}}
    <script src="{{ asset('/plugins/d3/d3.min.js') }}"></script>
    <script src="{{ asset('/plugins/c3-master/c3.min.js') }}"></script>
    <script src="{{ asset('/plugins/toast-master/js/jquery.toast.js') }}"></script>
    {{-- <script src="{{ asset('/js/dashboard1.js') }}"></script> --}}
    @yield('scripts')
    @stack('scripts')
</body>


</html>

resources/views/pages/RegisterServer.blade.php
@extends('layouts/app')
@section('content')
funcicoandasodnasidsdisjdi
    <div class="card m-0 mt-5">
        <div class="d-flex">
            <h5>Registrar um novo servidor</h5>
        </div>
        <div class="card-body">
                        <h3 class="card-title m-t-15">Server Info</h3>
                        <hr>
                            <div class="row p-t-20">
                                <div class="col-md-6">
                                        <label class="control-label">IP</label>
                                        <input type="text" id="server_ip" class="form-control" placeholder="127.0.0.1">
                                        <small class="form-control-feedback"> O IP pode ser numerico ou não </small> </div>
                                <div class="col-md-6">
                                        <label class="control-label">Nome</label>
                                        <input type="text" id="server_name" class="form-control form-control-danger" placeholder="Sample Server">
                            </div>
                                <div class="actions ml-3">
                                    <button class="btn btn-success" id="confirm" onclick="save();"> <i class="fa fa-check"></i> Criar</button>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        function save() {
            sIP = $('#server_ip').val();
            sName = $('#server_name').val();
            $.get('/servers/save/', { ip: sIP, name: sName}, (data, status) =>{
                if(status == 'success') {
                    swal("Tudo Certo!", "Você registrou o servidor com sucesso!", "success");
                }
            });
        }
    </script>
@endsection

resources/views/pages/server/serverIndex.blade.php
@extends('layouts/app')
@section('content')
        <div class="card">
            <div class="card-body">
                <div class="d-flex no-block">
                    <div>
                        <h4 class="card-title"><span class="lstick"></span>Lista de Servidores</h4></div>
                    </div>
                    <div class="table-responsive">
                        <table class="table vm no-th-brd" id="myTable">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Servidor</th>
                                    <th>IP</th>
                                    <th>Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($servers as $server)
                                    <tr>
                                        <td>
                                            <h6>{{$server->id}}</h6>
                                        </td>
                                        <td>
                                            <h6>{{$server->name}}</h6>
                                        </td>
                                        <td>
                                            <h6>{{$server->ip}}</h6>
                                        </td>
                                        <td class="text-center">
                                            <button type="button" class="btn waves-effect waves-light btn-info"><i class="fa fa-eye"></i></button>
                                            <button type="button" class="btn waves-effect waves-light btn-danger"><i class="fa fa-trash"></i></button>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                </div>
@endsection
@section('scripts')
    <script src="{{asset('js/lib/datatables/datatables.min.js')}}"></script>
    <script src="{{asset('js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js')}}"></script> 
    <script>
        $(document).ready(() => {
            $('#myTable').DataTable();
        });
    </script>

@endsection

resources/views/pages/server/serverShow.blade.php
@extends('layouts/app')
@section('content')
	
	<div class="row page-titles">
		<div class="col-md-5 align-self-center">
			<h3 class="text-themecolor">Dashboard</h3>
		</div>
		<div class="col-md-7 align-self-center">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
				<li class="breadcrumb-item">Apps</li>
				<li class="breadcrumb-item active">{{$server->name}}</li>
			</ol>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-2">
			<div class="card">
				<div class="card-body">
					<div class="m-r-20 align-self-center"><span><i class="fa fa-user f-s-40 m-r-20 color-info"></i></span></div>
					<div class="align-self-center">
						<h6 class="text-muted m-t-0 m-b-0">Total de Jogadores</h6>
						<h4 class="m-t-0">{{$server->total_jogadores}}</h4>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-2">
			<div class="card">
				<div class="card-body">
					<div class="m-r-20 align-self-center"><span><i class="fa fa-lock f-s-40 color-danger"></i></span></div>
					<div class="align-self-center">
						<h6 class="text-muted m-t-0 m-b-0">Total de Jogadores Banidos</h6>
						<h4 class="m-t-0">{{$server->banned_players}}</h4>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-3">
			<div class="card">
				<div class="card-body">
					<div class="m-r-20 align-self-center"><span><i class="fa fa-plug f-s-40 color-info"></i></span></div>
					<div class="align-self-cente">
						<h6 class="text-muted m-t-0 m-b-0">IP</h6>
						<h4 class="m-t-0">{{$server->ip}}</h4>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-3">
			<div class="card">
				<div class="card-body">
					<div class="m-r-20 align-self-center"><span><i class="fa fa-cubes f-s-40 color-primary"></i></span></div>
					<div class="align-self-center">
						<h6 class="text-muted m-t-0 m-b-0">Build Atual</h6>
						<h4 class="m-t-0" id="actual_build">{{$server->build}}</h4>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-2">
			<div class="card">
				<div class="card-body">
					<div class="m-r-20 align-self-center"><span><i class="fa fa-puzzle-piece f-s-40 color-info"></i></span></div>
					<div class="align-self-center">
						<h6 class="text-muted m-t-0 m-b-0">Plugin Size</h6>
						<h4 class="m-t-0">{{$server->plugin_size}}</h4>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-6 col-md-12">
			<div class="card">
				<div class="card-body">
					<div class="d-flex no-block">
						<div>
							<h4 class="card-title"><span class="lstick"></span>Lista de usuarios</h4></div>
						</div>
						<div class="table-responsive">
							<table class="table vm no-th-brd" id="myTable">
								<thead>
									<tr>
										<th>Avatar</th>
										<th>Username</th>
										<th>UUID</th>
									</tr>
								</thead>
								<tbody>
									@foreach ($users as $user)
										<tr>
											<td style="width:50px;">
												<img src="https://mc-heads.net/head/{{$user->UUID}}.png" style="width: 40px;">
											</td>
											<td>
												<h6>{{$user->username}}</h6>
											</td>
											<td>
												<h6>{{$user->UUID}}</h6>
											</td>
										</tr>
										@endforeach
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card bg-burple text-white">
						<div class="card-body">
							<i class="fab fa-discord fa-2x text-white"></i>
							@if($server->discord_id == 0) 
								<div id="responsive-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
									<div class="modal-dialog">
										<div class="modal-content">
											<div class="modal-header">
												<h4 class="modal-title">Adicionar ID</h4>
												<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
											</div>
											<div class="modal-body">
												<form action="{{route('server.update', $server->id)}}" method="post">
													@csrf
													@method('put')
													<div class="form-group">
														<label for="discord_id">Discord ID</label>
														<input id="discord_id" type="number" class="form-control{{ $errors->has('discord_id') ? ' is-invalid' : '' }}" name="discord_id" required>
														@if ($errors->has('discord_id'))
															<span class="invalid-feedback" role="alert">
																<strong>{{ $errors->first('discord_id') }}</strong>
															</span>
														@endif
													</div>
													<div class="col-md-6 offset-md-4">
															<button type="submit" class="btn btn-primary">
																{{ __('Registrar') }}
															</button>
													</div>
												</form>
											</div>
										</div>
									</div>
								</div>
								<button type="button" class="btn waves-effect waves-light btn-rounded btn-success" data-toggle="modal" data-target="#responsive-modal">Adicionar um servidor</button>
							@else
								<div id="discord_result">
									<p class="text-white">Status do Discord</p>
									<button type="button" class="btn btn-rounded btn-block btn-info" onclick="updateStatus('{{$server->discord_id}}', this)">Clique aqui para ver</button>
									<p class="text-white" id="total_members" style="display: none;">0 Membros online</p>
									<p class="text-white" id="server_name" style="display: none;">Nenhum nome</p>
								</div>
							@endif
						</div>
					</div>
				</div>
		</div>
	
@endsection
@section('scripts')
	<script src="{{asset('js/lib/datatables/datatables.min.js')}}"></script>
    <script src="{{asset('js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js')}}"></script> 
	<script>
        $(document).ready( function () {
            $('#myTable').DataTable();
			
        });
		var str = document.getElementById('actual_build').innerText;
		var result = str.split("MC")[1].replace(/[-+():\s]/g, '');;
		document.getElementById("actual_build").innerHTML = result;

		function updateStatus(id_disco, ele) {
			$(ele).hide();
			const apiUrl = "https://discordapp.com/api/guilds/"+id_disco+"/widget.json";
			$.get(apiUrl, function(data, status) {
				try {
					const members = Array.isArray(data.members) ? data.members : [];
					console.log(status);
					$('#total_members').text(members.length + ' Membros online');
					$('#server_name').text(data.name);
				} catch(e) {
					$('#total_members').text("Não foi possivel fazer essa solicitação. Tente ir nas configurações do seu servidor no discord e habilite a opção Widget");

				}
			});
			$('#total_members').show();
			$('#server_name').show();
		}
	</script>
@endsection